Resources:
  demo_ec2_instance:
    Type: AWS::EC2::Instance
    Properties:
      AdditionalInfo: String
      Affinity: String
      AvailabilityZone: String
      ImageId: String
      InstanceType: String
      KeyName: String
      SecurityGroupIds: 
        - String
      SecurityGroups: 
        - String
